Shuai_Yuan_Hw_1
cfss-fa19/hw01 pull request #63
Opened 2019-10-08 16:52 UTC by ys199569

The final version of Shuai Yuan homework 1. Work flow can be seen clearly from each commit and push.

2019-10-09 14:12 UTC, guivann commented on README.md
> +##**Basic Information**
There should be a space after the pound

2019-10-09 14:31 UTC, guivann commented on README.md
> +![Shuai Yuan 2016.](C:/Users/Admin/Desktop/Computing for Social Science/Shuai Yuan-hw1/Shuai Yuan hw-1/Shuai Yuan.png)
This directory only works on your own computer. I see that you already uploaded the image to GitHub and, thus, I believe this should work:
`![Shuai Yuan 2016.](Shuai Yuan.png)`

2019-10-09 14:44 UTC, guivann commented on README.md
> +##**Coursework Relvant to R**##
Typo

2019-10-09 14:45 UTC, guivann requested changes
I can definitely tell how much effort you put in. I like the multi-layer lists. Some minor changes should make this introduction perfect.

2019-10-10 15:16 UTC, bensoltoff reviewed
Evaluation
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |           |       x       |            |
| **Coding strategy**         |           |    x          |            |
| **Presentation**            |           |       x       |            |
| **Achievement, creativity** |           |        x      |            |
| **Ease of access**          |           |       x       |            |

2019-10-10 15:16 UTC, bensoltoff commented on README.md
> +![Shuai Yuan 2016.](C:/Users/Admin/Desktop/Computing for Social Science/Shuai Yuan-hw1/Shuai Yuan hw-1/Shuai Yuan.png)
Correct. We'll talk in future weeks about best practices for identifying the locations of files

2019-10-10 15:16 UTC, bensoltoff commented on README.md
> +* 1.Statistics I: Basics
You can actually make use of numbered lists in Markdown to format this list

```
1. Statistics I: Basics
    + Probability Theory
    + Hypothesis Testing 
        - Doing t-tests
1. Statistics II: Regression Analysis
    + Multivariant Regression 
        - Interaction    
    + Logistical Regression
    + Difference in Difference
    + Instrumental Variable
```

1. Statistics I: Basics
    + Probability Theory
    + Hypothesis Testing 
        - Doing t-tests
1. Statistics II: Regression Analysis
    + Multivariant Regression 
        - Interaction    
    + Logistical Regression
    + Difference in Difference
    + Instrumental Variable

2019-10-10 15:16 UTC, closed without merging